### ISSUE TITLE
MutCount -> separated: need functional tests

### ISSUE THREAD

**Issue by lecorguille** [abims-sbr/adaptsearch_old#18]
Hi @Mataivic,

You only set one test for the concat method but we should have test also for the "separated" method for both nuc and aa.

I couldn't [remove the zips](https://github.com/abims-sbr/adaptsearch/pull/16) because I'm not sure that I will not broke something

**Comment by alimatai** [comment]
@lecorguille 
It's done : zip removal + last functional tests (new branch : mutcount_no_zip)
